app:
  ai:
    text-splitter:
      chunk-size: 800
      min-chunk-size-chars: 350
      min-chunk-length-to-embed: 5
      max-num-chunks: 10000
      keep-separator: true
  frontend:
    url: http://localhost:5173

logging:
  level:
    com.mikhailkarpov: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:talk_to_docs}
    username: ${POSTGRES_USER:docs_service}
    password: ${POSTGRES_PASSWORD:ch4ngeMe_local}
  ai:
    ollama:
      chat:
        model: qwen2.5
      embedding:
        model: nomic-embed-text
      init:
        pull-model-strategy: when_missing
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
  application:
    name: docs-service
  flyway:
    locations: classpath:db/migration,classpath:db/seed
  main:
    banner-mode: off
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
